### ISSUE TITLE
how to use tensorflow model

### ISSUE THREAD

**Issue by Arnold1** [rmccorm4/TRTIS-Go-Client#1]
Hi,

how can I use a tensorflow model with TensorRT Inference Server?

do you have an example (which loads a tensorflow model) which I can run on a AWS ec2 node - which uses a p3.2xlarge instance?

I want to compare TensorFlow Serving with TensorRT Inference Server...

**Comment by rmccorm4** [comment]
Hi @Arnold1 ,

Check out this section of the docs: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models

If you're still having trouble, you'll want to ask this in https://github.com/nvidia/tensorrt-inference-server instead.
